/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#5d5f5f",
        "on-primary-container": "#636565",
        "outline-variant": "rgba(255, 255, 255, 0.1)",
        "secondary-fixed-dim": "#c8c6c9",
        "surface-container-high": "rgba(30, 27, 46, 0.7)",
        "surface-container": "rgba(30, 27, 46, 0.5)",
        "on-primary-fixed-variant": "#454747",
        "on-secondary": "#303033",
        "on-surface-variant": "#a7a5b4",
        "inverse-on-surface": "#313032",
        "secondary-container": "#47464a",
        "secondary": "#c8c6c9",
        "tertiary-container": "#e3e1ea",
        "on-secondary-fixed-variant": "#47464a",
        "on-secondary-fixed": "#1b1b1e",
        "outline": "rgba(255, 255, 255, 0.2)",
        "surface-variant": "rgba(45, 42, 66, 0.6)",
        "on-secondary-container": "#b6b4b8",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#c6c6c7",
        "surface": "transparent",
        "surface-container-lowest": "rgba(10, 8, 16, 0.8)",
        "primary": "#e2dcfc",
        "on-tertiary-fixed-variant": "#46464d",
        "on-background": "#e5e1e4",
        "surface-container-low": "rgba(20, 17, 30, 0.6)",
        "on-primary": "#2f3131",
        "background": "#0b0814",
        "surface-container-highest": "rgba(45, 42, 66, 0.8)",
        "surface-tint": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#e3e1ea",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-container": "#64646b",
        "on-primary-fixed": "#1a1c1c",
        "inverse-surface": "#e5e1e4",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#c7c5ce",
        "surface-dim": "transparent",
        "surface-bright": "rgba(60, 56, 82, 0.5)",
        "on-tertiary-fixed": "#1b1b21",
        "on-surface": "#e5e1ea",
        "primary-container": "rgba(139, 92, 246, 0.2)",
        "secondary-fixed": "#e4e1e5",
        "on-tertiary": "#303037"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.5rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-width-content": "1200px",
        "max-width-chat": "900px",
        "xs": "4px",
        "margin-mobile": "16px",
        "sm": "8px",
        "lg": "24px",
        "base": "4px",
        "gutter": "20px",
        "margin-desktop": "48px",
        "xl": "32px",
        "md": "16px"
      },
      fontFamily: {
        "label-md": ["var(--font-plus-jakarta-sans)"],
        "headline-lg": ["var(--font-plus-jakarta-sans)"],
        "display": ["var(--font-plus-jakarta-sans)"],
        "body-lg": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-plus-jakarta-sans)"],
        "headline-md": ["var(--font-plus-jakarta-sans)"],
        "body-sm": ["var(--font-plus-jakarta-sans)"],
        "code-md": ["var(--font-jetbrains-mono)"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    }
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('@tailwindcss/typography'),
  ],
};
